<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>MenuBelt</text>

        <Action name="menubelt_popup">
        <icon></icon>
        <text>Pop Up Custom List</text>
        <whatsThis></whatsThis>
        <toolTip>Open the custom list menu at the cursor</toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="menubelt_edit">
        <icon></icon>
        <text>Configure MenuBelt</text>
        <whatsThis></whatsThis>
        <toolTip>Configure the lists and their actions</toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
